---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: order-service

namespace: shopping-cart-apps

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false

resources:
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: order-service
  app.kubernetes.io/part-of: shopping-cart

images:
  - name: shopping-cart-order
    newName: ghcr.io/wilddog64/shopping-cart-order
    newTag: latest
